### ISSUE TITLE
Switch to filtering by user name for filtering out recording messages

### ISSUE THREAD

**Issue by spbnick** [Scribery/cockpit#12]
Lookup "tlog" user ID upon initialization, and use it to filter out all recording log messages instead of looking up by a hard-coded UID.

**Comment by sabbaka** [comment]
Username will be also passed to Journal service.
Users list would be done with a drop-down, I think.

**Comment by spbnick** [comment]
This is unrelated to filtering the list of recordings by the recorded user in the UI. This is about filtering messages coming from tlog-rec-session from the rest of the logs. We need to do that by matching the _UID field to the uid of user `tlog`.

**Comment by sabbaka** [comment]
I added this, for now it's in current pull request ( will see, maybe I will rebase or something else ). I will also add a check up, if UID won't be fetched - then there will be an error displayed, but this could go in next milestone. But it's working for our own convenience already.
Also, I will add loader, because getting of UID is async and it comes before showing items and for some short time there is just "no records".

**Comment by sabbaka** [comment]
I'll close issue now, because pull request was accepted.
