### ISSUE TITLE
Consider changing font size instead of resizing

### ISSUE THREAD

**Issue by spbnick** [Scribery/cockpit#30]
When resizing of the player according to recording is implemented, consider changing font size to accommodate new number of rows and columns, while keeping the terminal size on the page the same. Allow the user to resize the terminal manually, but again change font size, not number of columns/rows.
This would remove the hassle of terminal size suddenly changing, playback control buttons moving, and scrollbars appearing/disappearing, which would force the viewer to scroll around, possibly missing something in playback and generally getting tired and irritated.

We might still need to allow user to change the number of rows and columns in the playback terminal, in case window resizes weren't recorded or were wrong.

**Comment by sabbaka** [comment]
This should be fairly easy.

**Comment by sabbaka** [comment]
I've been working on this issue today for some time.
And I've decided to checkout xterm.js, so basically there is already such feature - https://xtermjs.org/docs/api/addons/fit/

Also, good thing to do anyway is to remove padding - terminal looks much better like this IMO.
![screenshot from 2017-10-30 17-40-57](https://user-images.githubusercontent.com/5558501/32183407-85580262-bd99-11e7-81aa-e6805a40af15.png)

Speaking in general - I think it's good idea to add full screen support.

Also, one more idea which I have is to skip having fixed size parent div of terminal, but rather resize font size based on actual pixel width of parent div ( which will be changed on window resize ), but keep min-width - but tricky part here is a lot of calculations could be involved and in xterm.js they might be already done and done better because of canvas.

**Comment by spbnick** [comment]
Thank you for your research, Kyrill, it sounds good. I was also wondering if xterm.js would be better, being better maintained and using canvas. What would be drawbacks of switching to it, in your opinion?

**Comment by sabbaka** [comment]
`// if bold is broken, we can't
// use it in the terminal.
function isBoldBroken(document) {
  var body = document.getElementsByTagName('body')[0];
  var terminal = document.createElement('div');
  terminal.className = 'terminal';
  var line = document.createElement('div');
  var el = document.createElement('span');
  el.innerHTML = 'hello world';
  line.appendChild(el);
  terminal.appendChild(line);
  body.appendChild(terminal);
  var w1 = el.scrollWidth;
  el.style.fontWeight = 'bold';
  var w2 = el.scrollWidth;
  body.removeChild(terminal);
  return w1 !== w2;
}`

This is function from term.js, which check if bold font will break width, one more option for us to do same, but for font size.

As for pros/cons for xterm.js will provide answer soon.

**Comment by sabbaka** [comment]
Regarding `xterm.js` - currently, I've a problem with loading it using webpack. In particular - the problem is with loading js.map source maps files, this is already covered in xterm's issues though.

**Comment by sabbaka** [comment]
I've loaded it from dist, without building it, but fit addon was not loaded.
Cool thing is that I've just switched from term.js to xterm and it has worked. So, now, it's only about properly loading xterm module in our project which is doable for sure, just need some time to figure out.

**Comment by spbnick** [comment]
Sounds good!

**Comment by sabbaka** [comment]
Okay, so I've tried some different approaches to load xterm properly - no success - discussion is going on here about this issue with webpack: https://github.com/xtermjs/xterm.js/issues/1018 .
Though, it's working, but looks is broken, not sure why for now and result of fit method is also not what I've expected.

**Comment by sabbaka** [comment]
Xterm's method `fit` is not doing what I've expected unfortunately, it's changing cols and rows amount.
